<template>
    <!-- <div id=""></div> -->
    <!-- <div v-html="showDiff" /> -->
     <pre >{{ diffString }}</pre> 
</template>

<script>
// import '../assets/diff2html.min.css';
// import * as Diff2Html from '../assets/diff2html.min.js';
import { computed } from 'vue';
import 'diff2html/bundles/css/diff2html.min.css';
import * as Diff2Html from 'diff2html'; //TODO: Find a way to use local resources without NPM if possible?
// debugger;

// const props = defineProps({
//     diffString: String
// });

// const renderedDiff = computed(() => {
//     if (props.diffString) {
//         const configuration = {
//             drawFileList: true,
//             fileListToggle: false,
//             fileListStartVisible: false,
//             fileContentToggle: false,
//             matching: 'lines',
//             outputFormat: 'side-by-side',
//             synchronisedScroll: true,
//             highlight: true,
//             renderNothingWhenEmpty: false,
//         };
//         return Diff2Html.html(props.diffString, configuration);
//     }
//     return '';
// });

export default {
    name: 'DiffViewer',
    // data() {
    //     return {
    //         diffString: '--- a/server/vendor/golang.org/x/sys/unix/zsyscall_linux_mipsle.go\n+++ b/server/vendor/golang.org/x/sys/unix/zsyscall_linux_mipsle.go\n@@ -1035,6 +1035,17 @@ func Prctl(option int, arg2 uintptr, arg3 uintptr, arg4 uintptr, arg5 uintptr) (\n \n // THIS FILE IS GENERATED BY THE COMMAND AT THE TOP; DO NOT EDIT\n \n+func Pselect(nfd int, r *FdSet, w *FdSet, e *FdSet, timeout *Timespec, sigmask *Sigset_t) (n int, err error) {\n+\tr0, _, e1 := Syscall6(SYS_PSELECT6, uintptr(nfd), uintptr(unsafe.Pointer(r)), uintptr(unsafe.Pointer(w)), uintptr(unsafe.Pointer(e)), uintptr(unsafe.Pointer(timeout)), uintptr(unsafe.Pointer(sigmask)))\n+\tn = int(r0)\n+\tif e1 != 0 {\n+\t\terr = errnoErr(e1)\n+\t}\n+\treturn\n+}\n+\n+// THIS FILE IS GENERATED BY THE COMMAND AT THE TOP; DO NOT EDIT\n+\n func read(fd int, p []byte) (n int, err error) {\n \tvar _p0 unsafe.Pointer\n \tif len(p) > 0 {\n',
    //     };
    // },
    props: {
        diffString: {
            type: String,
            // required: true
        }
    },
    computed: {
        AAA(){
            console.log("TEST")
        }
    },
    methods: {
        showDiff() {
            debugger;
            // if (this.diffString) {
                const configuration = {
                    drawFileList: true,
                    fileListToggle: false,
                    fileListStartVisible: false,
                    fileContentToggle: false,
                    matching: 'lines',
                    outputFormat: 'side-by-side',
                    synchronisedScroll: true,
                    highlight: true,
                    renderNothingWhenEmpty: false,
                };
                return Diff2Html.html(this.diffString, configuration);
                // const diff2htmlUi = new Diff2HtmlUI(targetElement, this.diffString, configuration);
                // diff2htmlUi.draw();
                // diff2htmlUi.highlightCode();
            }
        // }
    }
};
</script>

<style scoped></style>